apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: event-backend:latest
          imagePullPolicy: Never  # Kindにロードしたローカルイメージを強制的に使用する
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres_password@db:5432/event_db"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend